name: AI Question Generator CI/CD

on:

  push:
    branches:
      - main
      - docker-deployment

  pull_request:
    branches:
      - main

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      # ==========================
      # CHECKOUT REPOSITORY
      # ==========================

      - name: Checkout Repository
        uses: actions/checkout@v4

      # ==========================
      # SETUP PYTHON
      # ==========================

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.11"

      # ==========================
      # INSTALL DEPENDENCIES
      # ==========================

      - name: Install Dependencies

        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ==========================
      # PYTHON VALIDATION
      # ==========================

      - name: Validate Python Files

        run: |
          python -m py_compile app.py

      # ==========================
      # BUILD DOCKER IMAGE
      # ==========================

      - name: Build Docker Image

        run: |
          docker build -t ai-question-generator .

      # ==========================
      # SUCCESS MESSAGE
      # ==========================

      - name: CI Success

        run: echo "CI/CD Pipeline completed successfully!"